apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: tanaka01
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: ""
    requests.memory: ""
    limits.cpu: ""
    limits.memory: ""
    pods: ""
